using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

public static class Constants
{
    public const int ElementsCount = 118;

    public static readonly ElementPTInformation[] Elements = new[]
    {
        new ElementPTInformation(1, "H", "Водород", "Hydrogen", ElementGroup.ReactiveNonmetal, -8.5f, 5.5f),
        new ElementPTInformation(2, "He", "Гелий", "Helium", ElementGroup.NobleGas, 8.5f, 5.5f),
        new ElementPTInformation(3, "Li", "Литий", "Lithium", ElementGroup.AlkaliMetal, -8.5f, 4.5f),
        new ElementPTInformation(4, "Be", "Бериллий", "Beryllium", ElementGroup.AlkalineEarthMetal, -7.5f, 4.5f),
        new ElementPTInformation(5, "B", "Бор", "Boron", ElementGroup.Metalloid, 3.5f, 4.5f),
        new ElementPTInformation(6, "C", "Углерод", "Carbon", ElementGroup.ReactiveNonmetal, 4.5f, 4.5f),
        new ElementPTInformation(7, "N", "Азот", "Nitrogen", ElementGroup.ReactiveNonmetal, 5.5f, 4.5f),
        new ElementPTInformation(8, "O", "Кислород", "Oxygen", ElementGroup.ReactiveNonmetal, 6.5f, 4.5f),
        new ElementPTInformation(9, "F", "Фтор", "Fluorine", ElementGroup.ReactiveNonmetal, 7.5f, 4.5f),
        new ElementPTInformation(10, "Ne", "Неон", "Neon", ElementGroup.NobleGas, 8.5f, 4.5f),
        new ElementPTInformation(11, "Na", "Натрий", "Sodium", ElementGroup.AlkaliMetal, -8.5f, 3.5f),
        new ElementPTInformation(12, "Mg", "Магний", "Magnesium", ElementGroup.AlkalineEarthMetal, -7.5f, 3.5f),
        new ElementPTInformation(13, "Al", "Алюминий", "Aluminium", ElementGroup.PostTransitionMetal, 3.5f, 3.5f),
        new ElementPTInformation(14, "Si", "Кремний", "Silicon", ElementGroup.Metalloid, 4.5f, 3.5f),
        new ElementPTInformation(15, "P", "Фосфор", "Phosphorus", ElementGroup.ReactiveNonmetal, 5.5f, 3.5f),
        new ElementPTInformation(16, "S", "Сера", "Sulfur", ElementGroup.ReactiveNonmetal, 6.5f, 3.5f),
        new ElementPTInformation(17, "Cl", "Хлор", "Chlorine", ElementGroup.ReactiveNonmetal, 7.5f, 3.5f),
        new ElementPTInformation(18, "Ar", "Аргон", "Argon", ElementGroup.NobleGas, 8.5f, 3.5f),
        new ElementPTInformation(19, "K", "Калий", "Potassium", ElementGroup.AlkaliMetal, -8.5f, 2.5f),
        new ElementPTInformation(20, "Ca", "Кальций", "Calcium", ElementGroup.AlkalineEarthMetal, -7.5f, 2.5f),
        new ElementPTInformation(21, "Sc", "Скандий", "Scandium", ElementGroup.TransitionMetal, -6.5f, 2.5f),
        new ElementPTInformation(22, "Ti", "Титан", "Titanium", ElementGroup.TransitionMetal, -5.5f, 2.5f),
        new ElementPTInformation(23, "V", "Ванадий", "Vanadium", ElementGroup.TransitionMetal, -4.5f, 2.5f),
        new ElementPTInformation(24, "Cr", "Хром", "Chromium", ElementGroup.TransitionMetal, -3.5f, 2.5f),
        new ElementPTInformation(25, "Mn", "Марганец", "Manganese", ElementGroup.TransitionMetal, -2.5f, 2.5f),
        new ElementPTInformation(26, "Fe", "Железо", "Iron", ElementGroup.TransitionMetal, -1.5f, 2.5f),
        new ElementPTInformation(27, "Co", "Кобальт", "Cobalt", ElementGroup.TransitionMetal, -.5f, 2.5f),
        new ElementPTInformation(28, "Ni", "Никель", "Nickel", ElementGroup.TransitionMetal, .5f, 2.5f),
        new ElementPTInformation(29, "Cu", "Медь", "Copper", ElementGroup.TransitionMetal, 1.5f, 2.5f),
        new ElementPTInformation(30, "Zn", "Цинк", "Zinc", ElementGroup.TransitionMetal, 2.5f, 2.5f),
        new ElementPTInformation(31, "Ga", "Галлий", "Gallium", ElementGroup.PostTransitionMetal, 3.5f, 2.5f),
        new ElementPTInformation(32, "Ge", "Германий", "Germanium", ElementGroup.Metalloid, 4.5f, 2.5f),
        new ElementPTInformation(33, "As", "Мышьяк", "Arsenic", ElementGroup.Metalloid, 5.5f, 2.5f),
        new ElementPTInformation(34, "Se", "Селен", "Selenium", ElementGroup.ReactiveNonmetal, 6.5f, 2.5f),
        new ElementPTInformation(35, "Br", "Бром", "Bromine", ElementGroup.ReactiveNonmetal, 7.5f, 2.5f),
        new ElementPTInformation(36, "Kr", "Криптон", "Krypton", ElementGroup.NobleGas, 8.5f, 2.5f),
        new ElementPTInformation(37, "Rb", "Рубидий", "Rubidium", ElementGroup.AlkaliMetal, -8.5f, 1.5f),
        new ElementPTInformation(38, "Sr", "Стронций", "Strontium", ElementGroup.AlkalineEarthMetal, -7.5f, 1.5f),
        new ElementPTInformation(39, "Y", "Иттрий", "Yttrium", ElementGroup.TransitionMetal, -6.5f, 1.5f),
        new ElementPTInformation(40, "Zr", "Цирконий", "Zirconium", ElementGroup.TransitionMetal, -5.5f, 1.5f),
        new ElementPTInformation(41, "Nb", "Ниобий", "Niobium", ElementGroup.TransitionMetal, -4.5f, 1.5f),
        new ElementPTInformation(42, "Mo", "Молибден", "Molybdenum", ElementGroup.TransitionMetal, -3.5f, 1.5f),
        new ElementPTInformation(43, "Tc", "Технеций", "Technetium", ElementGroup.TransitionMetal, -2.5f, 1.5f),
        new ElementPTInformation(44, "Ru", "Рутений", "Ruthenium", ElementGroup.TransitionMetal, -1.5f, 1.5f),
        new ElementPTInformation(45, "Rh", "Родий", "Rhodium", ElementGroup.TransitionMetal, -.5f, 1.5f),
        new ElementPTInformation(46, "Pd", "Палладий", "Palladium", ElementGroup.TransitionMetal, .5f, 1.5f),
        new ElementPTInformation(47, "Ag", "Серебро", "Silver", ElementGroup.TransitionMetal, 1.5f, 1.5f),
        new ElementPTInformation(48, "Cd", "Кадмий", "Cadmium", ElementGroup.TransitionMetal, 2.5f, 1.5f),
        new ElementPTInformation(49, "In", "Индий", "Indium", ElementGroup.PostTransitionMetal, 3.5f, 1.5f),
        new ElementPTInformation(50, "Sn", "Олово", "Tin", ElementGroup.PostTransitionMetal, 4.5f, 1.5f),
        new ElementPTInformation(51, "Sb", "Сурьма", "Antimony", ElementGroup.Metalloid, 5.5f, 1.5f),
        new ElementPTInformation(52, "Te", "Теллур", "Tellurium", ElementGroup.Metalloid, 6.5f, 1.5f),
        new ElementPTInformation(53, "I", "Иод", "Iodine", ElementGroup.ReactiveNonmetal, 7.5f, 1.5f),
        new ElementPTInformation(54, "Xe", "Ксенон", "Xenon", ElementGroup.NobleGas, 8.5f, 1.5f),
        new ElementPTInformation(55, "Cs", "Цезий", "Caesium", ElementGroup.AlkaliMetal, -8.5f, .5f),
        new ElementPTInformation(56, "Ba", "Барий", "Barium", ElementGroup.AlkalineEarthMetal, -7.5f, .5f),
        new ElementPTInformation(57, "La", "Лантан", "Lanthanum", ElementGroup.Lanthanide, -6.5f, .5f),
        new ElementPTInformation(58, "Ce", "Церий", "Cerium", ElementGroup.Lanthanide, -5.5f, -2),
        new ElementPTInformation(59, "Pr", "Празеодим", "Praseodymium", ElementGroup.Lanthanide, -4.5f, -2),
        new ElementPTInformation(60, "Nd", "Неодим", "Neodymium", ElementGroup.Lanthanide, -3.5f, -2),
        new ElementPTInformation(61, "Pm", "Прометий", "Promethium", ElementGroup.Lanthanide, -2.5f, -2),
        new ElementPTInformation(62, "Sm", "Самарий", "Samarium", ElementGroup.Lanthanide, -1.5f, -2),
        new ElementPTInformation(63, "Eu", "Европий", "Europium", ElementGroup.Lanthanide, -.5f, -2),
        new ElementPTInformation(64, "Gd", "Гадолиний", "Gadolinium", ElementGroup.Lanthanide, .5f, -2),
        new ElementPTInformation(65, "Tb", "Тербий", "Terbium", ElementGroup.Lanthanide, 1.5f, -2),
        new ElementPTInformation(66, "Dy", "Диспрозий", "Dysprosium", ElementGroup.Lanthanide, 2.5f, -2),
        new ElementPTInformation(67, "Ho", "Гольмий", "Holmium", ElementGroup.Lanthanide, 3.5f, -2),
        new ElementPTInformation(68, "Er", "Эрбий", "Erbium", ElementGroup.Lanthanide, 4.5f, -2),
        new ElementPTInformation(69, "Tm", "Тулий", "Thulium", ElementGroup.Lanthanide, 5.5f, -2),
        new ElementPTInformation(70, "Yb", "Иттербий", "Ytterbium", ElementGroup.Lanthanide, 6.5f, -2),
        new ElementPTInformation(71, "Lu", "Лютеций", "Lutetium", ElementGroup.Lanthanide, 7.5f, -2),
        new ElementPTInformation(72, "Hf", "Гафний", "Hafnium", ElementGroup.TransitionMetal, -5.5f, .5f),
        new ElementPTInformation(73, "Ta", "Тантал", "Tantalum", ElementGroup.TransitionMetal, -4.5f, .5f),
        new ElementPTInformation(74, "W", "Вольфрам", "Tungsten", ElementGroup.TransitionMetal, -3.5f, .5f),
        new ElementPTInformation(75, "Re", "Рений", "Rhenium", ElementGroup.TransitionMetal, -2.5f, .5f),
        new ElementPTInformation(76, "Os", "Осмий", "Osmium", ElementGroup.TransitionMetal, -1.5f, .5f),
        new ElementPTInformation(77, "Ir", "Иридий", "Iridium", ElementGroup.TransitionMetal, -.5f, .5f),
        new ElementPTInformation(78, "Pt", "Платина", "Platinum", ElementGroup.TransitionMetal, .5f, .5f),
        new ElementPTInformation(79, "Au", "Золото", "Gold", ElementGroup.TransitionMetal, 1.5f, .5f),
        new ElementPTInformation(80, "Hg", "Ртуть", "Mercury", ElementGroup.TransitionMetal, 2.5f, .5f),
        new ElementPTInformation(81, "Tl", "Таллий", "Thallium", ElementGroup.PostTransitionMetal, 3.5f, .5f),
        new ElementPTInformation(82, "Pb", "Свинец", "Lead", ElementGroup.PostTransitionMetal, 4.5f, .5f),
        new ElementPTInformation(83, "Bi", "Висмут", "Bismuth", ElementGroup.PostTransitionMetal, 5.5f, .5f),
        new ElementPTInformation(84, "Po", "Полоний", "Polonium", ElementGroup.PostTransitionMetal, 6.5f, .5f),
        new ElementPTInformation(85, "At", "Астат", "Astatine", ElementGroup.PostTransitionMetal, 7.5f, .5f),
        new ElementPTInformation(86, "Rn", "Радон", "Radon", ElementGroup.NobleGas, 8.5f, .5f),
        new ElementPTInformation(87, "Fr", "Франций", "Francium", ElementGroup.AlkaliMetal, -8.5f, -.5f),
        new ElementPTInformation(88, "Ra", "Радий", "Radium", ElementGroup.AlkalineEarthMetal, -7.5f, -.5f),
        new ElementPTInformation(89, "Ac", "Актиний", "Actinium", ElementGroup.Actinide, -6.5f, -.5f),
        new ElementPTInformation(90, "Th", "Торий", "Thorium", ElementGroup.Actinide, -5.5f, -3),
        new ElementPTInformation(91, "Pa", "Протактиний", "Protactinium", ElementGroup.Actinide, -4.5f, -3),
        new ElementPTInformation(92, "U", "Уран", "Uranium", ElementGroup.Actinide, -3.5f, -3),
        new ElementPTInformation(93, "Np", "Нептуний", "Neptunium", ElementGroup.Actinide, -2.5f, -3),
        new ElementPTInformation(94, "Pu", "Плутоний", "Plutonium", ElementGroup.Actinide, -1.5f, -3),
        new ElementPTInformation(95, "Am", "Америций", "Americium", ElementGroup.Actinide, -.5f, -3),
        new ElementPTInformation(96, "Cm", "Кюрий", "Curium", ElementGroup.Actinide, .5f, -3),
        new ElementPTInformation(97, "Bk", "Берклий", "Berkelium", ElementGroup.Actinide, 1.5f, -3),
        new ElementPTInformation(98, "Cf", "Калифорний", "Californium", ElementGroup.Actinide, 2.5f, -3),
        new ElementPTInformation(99, "Es", "Эйнштейний", "Einsteinium", ElementGroup.Actinide, 3.5f, -3),
        new ElementPTInformation(100, "Fm", "Фермий", "Fermium", ElementGroup.Actinide, 4.5f, -3),
        new ElementPTInformation(101, "Md", "Менделевий", "Mendelevium", ElementGroup.Actinide, 5.5f, -3),
        new ElementPTInformation(102, "No", "Нобелий", "Nobelium", ElementGroup.Actinide, 6.5f, -3),
        new ElementPTInformation(103, "Lr", "Лоуренсий", "Lawrencium", ElementGroup.Actinide, 7.5f, -3),
        new ElementPTInformation(104, "Rf", "Резерфордий", "Rutherfordium", ElementGroup.TransitionMetal, -5.5f, -.5f),
        new ElementPTInformation(105, "Db", "Дубний", "Dubnium", ElementGroup.TransitionMetal, -4.5f, -.5f),
        new ElementPTInformation(106, "Sg", "Сиборгий", "Seaborgium", ElementGroup.TransitionMetal, -3.5f, -.5f),
        new ElementPTInformation(107, "Bh", "Борий", "Bohrium", ElementGroup.TransitionMetal, -2.5f, -.5f),
        new ElementPTInformation(108, "Hs", "Хассий", "Hassium", ElementGroup.TransitionMetal, -1.5f, -.5f),
        new ElementPTInformation(109, "Mt", "Мейтнерий", "Meitnerium", ElementGroup.UnknownProperties, -.5f, -.5f),
        new ElementPTInformation(110, "Ds", "Дармштадтий", "Darmstadtium", ElementGroup.UnknownProperties, .5f, -.5f),
        new ElementPTInformation(111, "Rg", "Рентгений", "Roentgenium", ElementGroup.UnknownProperties, 1.5f, -.5f),
        new ElementPTInformation(112, "Cn", "Коперниций", "Copernicium", ElementGroup.UnknownProperties, 2.5f, -.5f),
        new ElementPTInformation(113, "Nh", "Нихоний", "Nihonium", ElementGroup.UnknownProperties, 3.5f, -.5f),
        new ElementPTInformation(114, "Fl", "Флеровий", "Flerovium", ElementGroup.UnknownProperties, 4.5f, -.5f),
        new ElementPTInformation(115, "Mc", "Московий", "Moscovium", ElementGroup.UnknownProperties, 5.5f, -.5f),
        new ElementPTInformation(116, "Lv", "Ливерморий", "Livermorium", ElementGroup.UnknownProperties, 6.5f, -.5f),
        new ElementPTInformation(117, "Ts", "Теннессин", "Tennessine", ElementGroup.UnknownProperties, 7.5f, -.5f),
        new ElementPTInformation(118, "Og", "Оганесон", "Oganesson", ElementGroup.UnknownProperties, 8.5f, -.5f),
    };

    public static readonly Dictionary<ElementGroup, (Color backColor, Color textColor)> PTColors =
        new Dictionary<ElementGroup, (Color backColor, Color textColor)>()
        {
            { ElementGroup.AlkaliMetal, (new Color(.85f, .97f, 1), new Color(.13f, .5f, .56f)) },
            { ElementGroup.AlkalineEarthMetal, (new Color(1, .91f, .91f), new Color(.87f, .2f, .2f)) },
            { ElementGroup.TransitionMetal, (new Color(.96f, .91f, .99f), new Color(.4f, .2f, .93f)) },
            { ElementGroup.PostTransitionMetal, (new Color(.82f, .94f, .88f), new Color(.25f, .38f, .25f)) },
            { ElementGroup.Metalloid, (new Color(1, 1, .82f), new Color(.51f, .51f, .14f)) },
            { ElementGroup.ReactiveNonmetal, (new Color(.89f, .93f, 1), new Color(.13f, .42f, .94f)) },
            { ElementGroup.NobleGas, (new Color(1, .91f, .91f), new Color(.81f, .12f, .37f)) },
            { ElementGroup.Lanthanide, (new Color(.87f, 1, 1), new Color(.08f, .27f, .46f)) },
            { ElementGroup.Actinide, (new Color(1, .93f, .87f), new Color(.82f, .31f, .19f)) },
            { ElementGroup.UnknownProperties, (new Color(.87f, .87f, .87f), new Color(.31f, .31f, .31f)) },
        };

    public static readonly string[] ElementsGroupsNames = new[]
    {
        "Щелочной\nметалл",
        "Щелочноземельный\nметалл",
        "Переходный\nметалл",
        "Постпереходный\nметалл",
        "Полуметалл",
        "Неметалл",
        "Благородный\nгаз",
        "Латаноид",
        "Актиноид",
        "Неизвестные\nсвойства",
    };
}
